export const connectionInputElement = document.getElementById("connection-input");
export const connectionStateElement = document.getElementById("connection-state");
export const clientNameInputElement = document.getElementById("username");
export const socketIdInputElement = document.getElementById("identifier");
export const fileInputElement = document.getElementById("file-input");
export const sendFilesButton = document.getElementById("send-files");
export const previewElement = document.getElementById("preview");
export const sendMessageButton = document.getElementById("send-message");
export const messageInputElement = document.getElementById("message");
export const messageElement = document.getElementById("messages");
export const historyElement = document.getElementById("history");
export const appBodyElement = document.querySelector(".app__body");
export const appHeadElement = document.querySelector(".app__head");
export const previewContainerElement = previewElement.parentElement;
export const messageContainerElement = messageElement.parentElement;
//# sourceMappingURL=interface.js.map